// <auto-generated />
namespace MVCBLOG_PROJE.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class YeniSutunlarUyeTablosuna : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(YeniSutunlarUyeTablosuna));
        
        string IMigrationMetadata.Id
        {
            get { return "202008081152079_YeniSutunlarUyeTablosuna"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
